---
# The format of this file is documented here:
# https://github.com/quarkusio/quarkus-bot/#triage-issues
features: [ALL]
workflowRunAnalysis:
  workflows: ["Quarkus CI"]
projectsClassic:
  rules:
    - labels: [area/hibernate-validator]
      project: 1
      issues: true
      pullRequests: true
