name: "Pull Request Build"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        java: [ 11 ]
    steps:
      - uses: actions/checkout@v2
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y-%m")"
        shell: bash
      - name: Cache Maven Repository
        id: cache-maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          # refresh cache every month to avoid unlimited growth
          key: maven-repo-pr-jdk-${{ matrix.java }}-${{ steps.get-date.outputs.date }}
      - name: Install JDK ${{ matrix.java }}
        # Uses sha for added security since tags can be updated
        uses: joschi/setup-jdk@e87a7cec853d2dd7066adf837fe12bf0f3d45e52
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: export LANG=en_US && mvn -B clean install
      - name: Delete Local Artifacts From Cache
        shell: bash
        run: rm -rf ~/.m2/repository/io/quarkiverse/githubapp
