name: Test downstream projects

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
      - '.all-contributorsrc'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
      - '.all-contributorsrc'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Get Date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y-%m")"
      shell: bash
    - name: Cache Maven Repository
      id: cache-maven
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        # refresh cache every month to avoid unlimited growth
        key: maven-repo-pr-downstream-${{ runner.os }}-${{ steps.get-date.outputs.date }}

    - name: Build with Maven
      run: mvn -B install --file pom.xml

    - name: Get project version
      id: get-version
      run: |
        echo "::set-output name=version::$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)"
      shell: bash

    - uses: actions/checkout@v2
      with:
        repository: quarkusio/quarkus-bot
        path: quarkus-bot

    - name: Update quarkus-github-app version in quarkus-bot
      run: mvn -B versions:set-property -Dproperty=quarkus-github-app.version -DnewVersion=${{ steps.get-version.outputs.version }}
      working-directory: quarkus-bot

    - name: Run quarkus-bot tests
      run: mvn -B install
      working-directory: quarkus-bot

    - uses: actions/checkout@v2
      with:
        repository: hibernate/hibernate-github-bot
        path: hibernate-github-bot

    - name: Update quarkus-github-app version in hibernate-github-bot
      run: mvn -B versions:set-property -Dproperty=quarkus-github-app.version -DnewVersion=${{ steps.get-version.outputs.version }}
      working-directory: hibernate-github-bot

    - name: Run hibernate-github-bot build (and tests, if any)
      run: mvn -B install
      working-directory: hibernate-github-bot

